#!/bin/bash

NAME="Go (Golang)"
BASE_REPO=golang
VARIANTS=(browsers node node-browsers)

IMAGE_CUSTOMIZATIONS='
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | INSTALL_DIRECTORY=/usr/local/bin sh
RUN cd /opt && wget https://github.com/gotestyourself/gotestsum/releases/download/v0.3.1/gotestsum_0.3.1_linux_amd64.tar.gz && tar zxvf gotestsum_0.3.1_linux_amd64.tar.gz && mv gotestsum /go/bin/ && rm -rf *
'

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
